/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          100: "hsl(var(--color-primary-100) / <alpha-value>)",
          200: "hsl(var(--color-primary-200) / <alpha-value>)",
          300: "hsl(var(--color-primary-300) / <alpha-value>)",
          400: "hsl(var(--color-primary-400) / <alpha-value>)",
          500: "hsl(var(--color-primary-500) / <alpha-value>)",
          600: "hsl(var(--color-primary-600) / <alpha-value>)",
          700: "hsl(var(--color-primary-700) / <alpha-value>)",
          800: "hsl(var(--color-primary-800) / <alpha-value>)",
          900: "hsl(var(--color-primary-900) / <alpha-value>)",
        },
        secondary: {
          100: "hsl(var(--color-secondary-100) / <alpha-value>)",
          200: "hsl(var(--color-secondary-200) / <alpha-value>)",
          300: "hsl(var(--color-secondary-300) / <alpha-value>)",
          400: "hsl(var(--color-secondary-400) / <alpha-value>)",
          500: "hsl(var(--color-secondary-500) / <alpha-value>)",
          600: "hsl(var(--color-secondary-600) / <alpha-value>)",
          700: "hsl(var(--color-secondary-700) / <alpha-value>)",
          800: "hsl(var(--color-secondary-800) / <alpha-value>)",
          900: "hsl(var(--color-secondary-900) / <alpha-value>)",
        },
        tertiary: {
          100: "hsl(var(--color-tertiary-100) / <alpha-value>)",
          200: "hsl(var(--color-tertiary-200) / <alpha-value>)",
          300: "hsl(var(--color-tertiary-300) / <alpha-value>)",
          400: "hsl(var(--color-tertiary-400) / <alpha-value>)",
          500: "hsl(var(--color-tertiary-500) / <alpha-value>)",
          600: "hsl(var(--color-tertiary-600) / <alpha-value>)",
          700: "hsl(var(--color-tertiary-700) / <alpha-value>)",
          800: "hsl(var(--color-tertiary-800) / <alpha-value>)",
          900: "hsl(var(--color-tertiary-900) / <alpha-value>)",
        },
        dark: {
          primary: {
            100: "hsl(var(--color-dark-primary-100) / <alpha-value>)",
            200: "hsl(var(--color-dark-primary-200) / <alpha-value>)",
            300: "hsl(var(--color-dark-primary-300) / <alpha-value>)",
            400: "hsl(var(--color-dark-primary-400) / <alpha-value>)",
            500: "hsl(var(--color-dark-primary-500) / <alpha-value>)",
            600: "hsl(var(--color-dark-primary-600) / <alpha-value>)",
            700: "hsl(var(--color-dark-primary-700) / <alpha-value>)",
            800: "hsl(var(--color-dark-primary-800) / <alpha-value>)",
            900: "hsl(var(--color-dark-primary-900) / <alpha-value>)",
          },
          secondary: {
            100: "hsl(var(--color-dark-secondary-100) / <alpha-value>)",
            200: "hsl(var(--color-dark-secondary-200) / <alpha-value>)",
            300: "hsl(var(--color-dark-secondary-300) / <alpha-value>)",
            400: "hsl(var(--color-dark-secondary-400) / <alpha-value>)",
            500: "hsl(var(--color-dark-secondary-500) / <alpha-value>)",
            600: "hsl(var(--color-dark-secondary-600) / <alpha-value>)",
            700: "hsl(var(--color-dark-secondary-700) / <alpha-value>)",
            800: "hsl(var(--color-dark-secondary-800) / <alpha-value>)",
            900: "hsl(var(--color-dark-secondary-900) / <alpha-value>)",
          },
          tertiary: {
            100: "hsl(var(--color-dark-tertiary-100) / <alpha-value>)",
            200: "hsl(var(--color-dark-tertiary-200) / <alpha-value>)",
            300: "hsl(var(--color-dark-tertiary-300) / <alpha-value>)",
            400: "hsl(var(--color-dark-tertiary-400) / <alpha-value>)",
            500: "hsl(var(--color-dark-tertiary-500) / <alpha-value>)",
            600: "hsl(var(--color-dark-tertiary-600) / <alpha-value>)",
            700: "hsl(var(--color-dark-tertiary-700) / <alpha-value>)",
            800: "hsl(var(--color-dark-tertiary-800) / <alpha-value>)",
            900: "hsl(var(--color-dark-tertiary-900) / <alpha-value>)",
          },
        },
      },
    },
  },
  plugins: [],
};
