import { type NextPage } from "next";
import LoginButton from "../components/common/LoginButton/LoginButton";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HammerTail</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginButton />
      <br />
      <Link href="/worlds">
        <span>Worlds</span>
      </Link>
    </>
  );
};

export default Home;
