-- AlterTable
ALTER TABLE `Page` ADD COLUMN `description` VARCHAR(191) NULL,
    ADD COLUMN `end` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `other` JSON NULL,
    ADD COLUMN `start` INTEGER NOT NULL DEFAULT 0;
